on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/7c32638f6a550c772f958b9dd9af6d82
          gist_title: 14-Motor-DCInfrarrojo-CCS-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/Motor DC + Infrarrojo.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/21c7aba5f81a0ffb06afc3e6aa64c080
          gist_title: 14-MotorDCInfrarrojo-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/Motor DC + Infrarrojo.c
          file_encoding: WINDOWS-1252